friend/urls.py
from django.urls import path, include

from . import views

app_name = 'friend'

urlpatterns = [
    
    path('users/<int:pk>/', views.otherprofilepageview, name='profile_view'),
    path('friends/', views.friends_list, name='friends'),
    path('send_friend_request/<int:pk>/', views.send_friend_request, name='send-friend-request'),
    path('cancel_friend_request/<int:pk>/', views.cancel_friend_request, name='cancel-friend-request'),
    path('accept_friend_request/<int:pk>/', views.accept_friend_request, name='accept-friend-request'),
    path('decline_friend_request/<int:pk>/', views.decline_friend_request, name='decline-friend-request'),
    path('delete_friend/<int:pk>/', views.delete_friend, name='delete-friend'),
]

messaging/urls.py
from django.urls import path

from . import views
from .views import direct_chat_room

app_name = 'messaging'

urlpatterns = [
    path('messenger/', views.messaging_page, name='messenger'),
    path('messenger/chat_room/<str:room_name>/', views.chat_room, name='chat-room'),
    path('messenger/direct_chat/<int:pk>/', views.direct_chat_room, name='direct-chat'),
]

pages/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from pages.views import SearchView
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage_view, name='home'),
    path('my-profile/<int:pk>/', views.myprofilepageview, name='my_profile'),
    path('user_search/', login_required(SearchView.as_view()), name='search'),
]

project_structure/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # Urls for our apps.
    path('', include('users.urls')),
    path('', include('pages.urls')),
    path('', include('friend.urls')),
    path('', include('videochat.urls')),
    path('', include('messaging.urls')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import SignUpView, CustomPasswordChangeView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    # Url using Django auth.
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    #Password reset
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name ='registration/password_reset.html',
  email_template_name = 'registration/password_reset_email.html', success_url = reverse_lazy('users:password_reset_done')), name= "reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:login')),name="password_reset_confirm"),
    
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(),name="password_reset_comlete"),
    #password change
    path('password_change/', CustomPasswordChangeView.as_view(),name='change_password'),
    path('delete_owner/', views.delete_owner, name="delete-owner"),
]

videochat/urls.py
from django.urls import path
from videochat import views

app_name = 'videochat'

urlpatterns = [
    path('videochatlobby/', views.videochatlobbyviews, name='lobby'),
    path('videochatroom/', views.videochatroomviews, name='room'),
    path('get_token/', views.getToken),
    path('privatevideochat/<int:pk>/', views.private_video_chat_room, name='private-video-chat'),
]

pages/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load crispy_forms_tags %}
{% load notifications_tags %}
    
<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"  type="text/css" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">

    {% block title %}

    <title>Squaak</title>

    {% endblock title %}


</head>
<body>


    <header>

        <nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'pages:home' %}"><h1 class="great-vibes">Squaak<i class="fa-solid fa-feather-pointed"></i></h1> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        
            {% if user.is_authenticated %}
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:home' %}">Home/Dashboard <i class="fa-solid fa-house-user"></i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'friend:friends' %}">Flock <i class="fa-solid fa-user-group"></i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'messaging:messenger' %}">Chat Rooms <i class="fa-solid fa-message"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'videochat:lobby' %}">Group Video Chat <i class="fa-solid fa-video"></i></a>
                  </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'pages:my_profile' user.pk %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'users:change_password' %}">Change Password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Sign out</a>
                  </div>
                </li>
              </ul>

                    <div class="dropdown">
                        <a href="#" class="notification dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true">
                          <i class="fa fa-bell" style="font-size:24px"></i>
                          <span class="badge">{% live_notify_badge %}</span>
                        </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                {% if user.notifications.unread %}
                                <a href="{% url 'notifications:mark_all_as_read' %}?next={{ request.path }}">Mark all as Read.</a>
                                <hr>
                                {% endif %}
                                {% for notification in user.notifications.unread|slice:"0:5" %}
                                    <div>
                                    <a href="{% url 'messaging:direct-chat' notification.actor.pk %}">Message from: {{ notification.actor }}</a> 
                                  <button class="dropdown-item" type="button">{{ notification.description }}</button>
                                  <a href="{% url 'notifications:mark_as_read' notification.slug %}?next={{ request.path }}">Mark As Read.</a>		
                                  </div>
                                  <div class="dropdown-divider"></div>
                                {% endfor %}
                            </div>
                          </div>
                          <div class="dropdown-divider"></div>
                    </div>
                  </div>
                {% live_notify_list list_class="dropdown-menu" %}

              <form id="search-bar" class="form-inline" action="{% url 'pages:search' %}" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Search for Friends" name="user_name">
                <button class="btn btn-info" type="submit">Search</button>
            </form>
        
            </div>
        
            {% else %}
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Sign in</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}" >Sign up</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:reset_password' %}" >Forgot Password?</a>
                    </li>
                    </div>
                  </li>
                </ul>
              </div>
        
              {% endif %}
        
          </nav>
    
    </header>

                    
        <div>
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
        
</body>

<style>
    body {
      background-color: #bb8ad2;
    }

    .notification {
      color: white;
      text-decoration: none;
      padding: 15px 26px;
      position: relative;
      display: inline-block;
      border-radius: 2px;
    }
     
    .notification .badge {
      position: absolute;
      top: 2px;
      right: 30px;
      padding: 5px 10px;
      border-radius: 50%;
      background-color: red;
      color: white;
    }

    @font-face {
      font-family: "great-vibes";
      src: local('great-vibes');
      src: url('{% static "fonts/GreatVibes-Regular.ttf" %}');
    }

    </style>
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
</html>

pages/templates/home.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load static %}


{% block content %}

    {% if user.is_authenticated %}

         <div class="jumbotron mx-auto mt-5" style="max-height: fit-content; min-width: 400px; max-width: 500px">
            <h1 class="display-4">Welcome to Squaak!</h1>
            <h2>Squaak is a Real-time communication application.</h2>
            <hr>
            <p class="lead mb-2">Squaak is a Web-application with video chat and real-time messaging capabilities.</p>
            <p class="lead mb-2">Squaak's Video Chat utilizes Agoras SDK and Agora Token Builder.</p>
            <p class="lead mb-2">Squaak's Messaging utilizes Django Channels and Web Sockets in order to provide RTC.</p>
            <p class="lead mb-2">The friends interface allows users to interact with one-another in various ways.</p>
            <p class="lead">The notifications in this web-app utilize Django notifications hq.</p>
            <hr class="my-4">
            <h1 class="lead">Friend System</h1>
            <hr>
            <h1>User May:</h1>
            <ul class="ml-4">
                <li>Add or Remove potential friends.</li>
                <li>Cancel their pending friend requests.</li>
                <li>They may also decline incoming friend requests.</li>
            </ul>
            <hr>
            <h1 class="lead">Video Chat</h1>
            <hr>
            <h1>User May:</h1>
            <ul class="ml-4">
                <li>Initiate 1 to 1 Video chat rooms with their friends.</li>
                <li>Create Group Video chat rooms.</li>
            </ul>
            <hr>
            <h1 class="lead">Real-time Messaging</h1>
            <hr>
            <h1>User May:</h1>
            <ul class="ml-4">
                <li>Initiate 1 to 1 Direct Messaging with their friends.</li>
                <li>Create / join Public Real-time chat rooms.</li>
            </ul>
        </div>
    {% else %}
         <div class="jumbotron mx-auto mt-5" style="max-height: fit-content; min-width: 400px; max-width: 500px">
            <h1 class="display-4 mb-3">Welcome to Squaak!</h1>
            <h2 class="lead">Squaak is a Real-time communication application.</h2>
            <hr>
            <p class="lead">The integrated friend system allows user to connect with their peers through video chat communication, and real-time text chat communication.</p>
            <hr class="my-4">
            <p class="mb-3" style="text-align: center;">Sign up to start now or login!</p>
            <div class="row justify-content-center" style="text-align: center;">
                <div class="col-xs-4 mr-4">
                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="{% url 'users:signup' %}" role="button">Sign up</a>
                    </p>
                </div>
                <div class="col-xs-4 ml-4">   
                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}" role="button">Sign in</a>
                    </p>
                </div>     
            </div>
        </div>
    {% endif %}
{% endblock content %}

pages/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<div class="container" style="max-width: auto; max-height: auto;">
  <div class="card border-info mt-3 mb-3" style="max-width: auto; max-height: auto;">
    <img id="profile-pic"class="card-img rounded-circle img-fluid mx-auto mt-2" style="max-height: 200px; max-width: 200px;" src="{{ user.profile.image.url }}">
    <div id="profile-text"class="card-body">
      <h1>Username:</h1>
      <h5 class="card-title">{{ user.username }}</h5>
      <h1>E-mail:</h1>
      <p class="card-text mb-2">{{ user.email }}</p>
      <h1>Bio:</h1>
      <p class="card-text">{{ user.profile.bio }}</p>
    </div>
  </div>
  </div>

  <div class="card text-white bg-dark mx-auto mt-4" style="width: 32rem;">
    <div class="card-body">
        <h5 class="card-title" style="text-align: center;">Edit Profile</h5>
        <hr>
    <form id="profile-form"method="post" enctype="multipart/form-data">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      {% csrf_token %}
      <fieldset class="form-group">
        {{ u_form|crispy }}
        {{ p_form|crispy }}
      </fieldset>
      <div class="form-group" style="display: block; text-align: center;">
          <button class="btn btn-info" type="submit">Update</button>
      </div>
    </form>
  </div>
</div>

  <div>
    <a href="{% url 'users:delete-owner' %}">
      <button type="button" class="btn btn-danger btn-sm btn-block mb-2 mt-4">
      Delete Account
      </button>
    </a>
  </div>

{% endblock content %}

pages/templates/search.html
{% extends "base.html" %}
{% block content %}

<div class="card-columns mt-5">
   {% for result in object_list %}
   
   {% if result in request.user.friends.all and result.username != request.user.username %}
   <div class="card border-success mb-3 text-center">
   {% else %}
   <div class="card border-info mb-3 text-center">
   {% endif %}
   
      <img class="card-img rounded-circle img-fluid" style="max-height: 200px; max-width: 200px;" src="{{ result.profile.image.url }}">
   
     <div class="card-header">{{ result.username }}</div>
     <div class="card-body text-info">
   
      {% if result.username == request.user.username %}
         <h5 class="card-title">Status: Current User</h5>
      {% endif %}
   
      {% if result not in request.user.friends.all and result.username != request.user.username %}
         <h5 class="card-title">Status: Not Friends</h5>
      {% elif result in request.user.friends.all and result.username != request.user.username %}
         <h5 class="card-title">Status: Friend</h5>
      {% endif %}
   
         <h1>Bio:</h1>
         <span class="card-text" style="display: inline-block; overflow: hidden; text-overflow: ellipsis;">{{ result.profile.bio | truncatechars:50 }}</span>
     </div>
   
     {% if result not in request.user.friends.all and result.username != request.user.username %}
     <div class="card-footer bg-transparent border-info">
        <a href="{% url 'friend:profile_view' result.pk %}">
         <button class="btn btn-primary">
            View Profile
         </button>
         </a>
   
         <a href="{% url 'friend:send-friend-request' result.pk %}">
          <button class="btn btn-primary">
             Send Friend Request
          </button>
         </a>
      </div>
      {% else %}
      <div class="card-footer bg-transparent border-info text-center">
         <a href="{% url 'friend:profile_view' result.pk %}">
          <button class="btn btn-success">
             View Profile
          </button>
       </a>
       </div>
       {% endif %}
   </div>
   
   {% endfor %}
   </div>

{% endblock content %}