friend/urls.py
from django.urls import path, include

from . import views

app_name = 'friend'

urlpatterns = [
    
    path('users/<int:pk>/', views.otherprofilepageview, name='profile_view'),
    path('friends/', views.friends_list, name='friends'),
    path('send_friend_request/<int:pk>/', views.send_friend_request, name='send-friend-request'),
    path('cancel_friend_request/<int:pk>/', views.cancel_friend_request, name='cancel-friend-request'),
    path('accept_friend_request/<int:pk>/', views.accept_friend_request, name='accept-friend-request'),
    path('decline_friend_request/<int:pk>/', views.decline_friend_request, name='decline-friend-request'),
    path('delete_friend/<int:pk>/', views.delete_friend, name='delete-friend'),
]

messaging/urls.py
from django.urls import path

from . import views
from .views import direct_chat_room

app_name = 'messaging'

urlpatterns = [
    path('messenger/', views.messaging_page, name='messenger'),
    path('messenger/chat_room/<str:room_name>/', views.chat_room, name='chat-room'),
    path('messenger/direct_chat/<int:pk>/', views.direct_chat_room, name='direct-chat'),
]

pages/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from pages.views import SearchView
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.homepage_view, name='home'),
    path('my-profile/<int:pk>/', views.myprofilepageview, name='my_profile'),
    path('user_search/', login_required(SearchView.as_view()), name='search'),
]

project_structure/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # Urls for our apps.
    path('', include('users.urls')),
    path('', include('pages.urls')),
    path('', include('friend.urls')),
    path('', include('videochat.urls')),
    path('', include('messaging.urls')),
    re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videochat/urls.py
from django.urls import path
from videochat import views

app_name = 'videochat'

urlpatterns = [
    path('videochatlobby/', views.videochatlobbyviews, name='lobby'),
    path('videochatroom/', views.videochatroomviews, name='room'),
    path('get_token/', views.getToken),
    path('privatevideochat/<int:pk>/', views.private_video_chat_room, name='private-video-chat'),
]

friend/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class FriendRequest(models.Model):
    """Friend request logic to issue friend request from sender to receiver."""

    # Sender and receiver can issue or approve multiple requests.
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver")

    is_active = models.BooleanField(blank=True, null=False, default=True)

    # As soon as a friend request is issued a timestamp is created.
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "From {}, to {}".format(self.sender.username, self.receiver.username)

friend/views.py
from webbrowser import get
from django.dispatch import receiver
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from messaging.models import PrivateChatRoom
from videochat.models import PrivateVideoChatRoom
from users.models import Profile, CustomUser
from .models import FriendRequest
from django.contrib import messages

# Create your views here.

# profile page view for other users.
def otherprofilepageview(request, pk):
    
    user = get_object_or_404(CustomUser, pk=pk)
    current_user = request.user
    sent_friend_request = FriendRequest.objects.filter(sender=current_user, receiver=user)

    context = {
        'user': user,
        'current_user': current_user,
        'sent_friend_request': sent_friend_request
    }

    return render(request, 'otherprofile.html', context)

# View for the users Friends list.
def friends_list(request):

    p = request.user
    friends = p.friends.all()

    sent_friend_requests = FriendRequest.objects.filter(sender=request.user)
    rec_friend_requests = FriendRequest.objects.filter(receiver=request.user)

    initiated_direct_chats = PrivateChatRoom.objects.filter(user1=request.user)
    received_direct_chats = PrivateChatRoom.objects.filter(user2=request.user)

    initiated_video_chats = PrivateVideoChatRoom.objects.filter(videouser1=request.user)
    received_video_chats = PrivateVideoChatRoom.objects.filter(videouser2=request.user)
    
    context = {
        'friends': friends,
        'sent_friend_requests': sent_friend_requests,
        'rec_friend_requests': rec_friend_requests,

        'initiated_direct_chats': initiated_direct_chats,
        'received_direct_chats': received_direct_chats,

        'initiated_video_chats': initiated_video_chats,
        'received_video_chats': received_video_chats,
    }
    return render(request, "friends.html", context)

# Function for sending a friend request.
@login_required
def send_friend_request(request, pk):

    sender = request.user
    receiver = CustomUser.objects.get(pk=pk)

    friend_request, created = FriendRequest.objects.get_or_create(sender=sender, receiver=receiver)

    if created:
        return redirect('friend:profile_view', pk=pk)
    else:
        return redirect('friend:profile_view', pk=pk)

# Function for cancelling a sent friend request.
def cancel_friend_request(request, pk):

    sender = request.user
    receiver = CustomUser.objects.get(pk=pk)

    friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)

    if friend_request.sender == request.user:
        friend_request.delete()
        messages.success(request, 'Friend Request Canceled.')
        return redirect('friend:profile_view', pk=pk)

# Function for accepting a friend request.
@login_required
def accept_friend_request(request, pk):

    friend_request = FriendRequest.objects.get(pk=pk)

    if friend_request.receiver == request.user:
        friend_request.receiver.friends.add(friend_request.sender)
        friend_request.sender.friends.add(friend_request.receiver)
        friend_request.delete()
        return redirect('friend:friends')
    else:
        decline_friend_request()

# Function for declining a friend request.
@login_required
def decline_friend_request(request, pk):

    friend_request = FriendRequest.objects.get(pk=pk)

    if friend_request.receiver == request.user:
        friend_request.delete()
        return redirect('friend:friends')
    else:
        accept_friend_request()

@login_required
def delete_friend(request,pk):

    user_account = request.user
    friend_account = CustomUser.objects.get(pk=pk)

    existing_messenger_initiated = PrivateChatRoom.objects.filter(user1=request.user, user2=friend_account)
    existing_messenger_received = PrivateChatRoom.objects.filter(user2=request.user, user1=friend_account)

    existing_videochat_initiated = PrivateVideoChatRoom.objects.filter(videouser1=request.user, videouser2=friend_account)
    existing_videochat_received = PrivateVideoChatRoom.objects.filter(videouser2=request.user, videouser1=friend_account)

    user_account.friends.remove(friend_account)
    friend_account.friends.remove(user_account)

    existing_messenger_initiated.delete()
    existing_messenger_received.delete()

    existing_videochat_initiated.delete()
    existing_videochat_received.delete()

    return redirect('friend:friends')

friend/templates/friends.html
{% extends "base.html" %}

{% block content %}

<div class="card-deck justify-content-center mt-5">

<div class="card text-black border-success mb-3 mx-auto" style="max-width: 18rem;">
    <div class="card-header text-center">Friends List</div>
    <div class="card-body">
    {% for friend in friends %}
      <h5 class="card-title text-center">{{ friend.username }}</h5>
      <a href="{% url 'friend:profile_view' friend.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        View Profile
        </button>
      </a>
      <a href="{% url 'friend:delete-friend' friend.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Remove from Friends
        </button>
      </a>
      <hr>
    {% endfor %}
    </div>
  </div>

  <div class="card text-black border-warning mb-3 mx-auto" style="max-width: 18rem;">
    <div class="card-header text-center">Friend Requests</div>
    <div class="card-body">
        {% for request in rec_friend_requests %}
      <h5 class="card-title text-center">From: {{ request.sender }}</h5>
      <a href="{% url 'friend:accept-friend-request' request.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Accept Friend Request
        </button>
      </a>
      <a href="{% url 'friend:decline-friend-request' request.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Decline Friend Request
        </button>
      </a>
      <hr>
      {% endfor %}
      <div class="card-header text-center">Requests Sent</div>
    <div class="card-body">
        {% for sent in sent_friend_requests %}
      <h5 class="card-title text-center">Send to: {{ sent.receiver }}</h5>
      <a href="{% url 'friend:cancel-friend-request' sent.receiver.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Cancel Friend Request
        </button>
      </a>
      {% endfor %}
    
    </div>
  </div>
  </div>

  <div class="card text-black border-info mb-3 mx-auto" style="max-width: 18rem;">
    <div class="card-header text-center">Direct Messages</div>
    <div class="card-body">
        <div class="card-header text-center">-Initiated-</div>
        {% for ini in initiated_direct_chats %}
      <h5 class="card-title text-center">Chatting with: {{ ini.user2 }}</h5>
      <a href="{% url 'messaging:direct-chat' ini.user2.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Message {{ ini.user2 }}
        </button>
      </a>
      <hr>
      {% endfor %}
      <div class="card-header text-center">-Received-</div>
    <div class="card-body">
        {% for rec in received_direct_chats %}
      <h5 class="card-title text-center">Chatting with: {{ rec.user1 }}</h5>
      <a href="{% url 'messaging:direct-chat' rec.user1.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Message {{ rec.user1 }}
        </button>
      </a>
      {% endfor %}
    
    </div>
  </div>
  </div>

  <div class="card text-black border-info mb-3 mx-auto" style="max-width: 18rem;">
    <div class="card-header text-center">Video Chat Rooms</div>
    <div class="card-body">
        <div class="card-header text-center">-Initiated-</div>
        {% for inivid in initiated_video_chats %}
      <h5 class="card-title text-center">Video Chatting with: {{ inivid.videouser2 }}</h5>
      <a href="{% url 'videochat:private-video-chat' inivid.videouser2.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Jump into Videochat Room
        </button>
      </a>
      <hr>
      {% endfor %}
      <div class="card-header text-center">-Received-</div>
    <div class="card-body">
        {% for recvid in received_video_chats %}
      <h5 class="card-title text-center">Video Chatting with: {{ recvid.videouser1 }}</h5>
      <a href="{% url 'videochat:private-video-chat' recvid.videouser1.pk %}">
        <button type="button" class="btn btn-info btn-sm btn-block mb-2">
        Jump into Videochat Room
        </button>
      </a>
      {% endfor %}
    
    </div>
  </div>
  </div>

</div>
{% endblock content %}

friend/templates/otherprofile.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

<div class="container" style="max-width: auto; max-height: auto;">
  <div class="card border-info mt-3" style="max-width: auto; max-height: auto;">
    <img id="profile-pic"class="card-img rounded-circle img-fluid mx-auto mt-2" style="max-height: 200px; max-width: 200px;" src="{{ user.profile.image.url }}">
    <div id="profile-text"class="card-body">
      <h1>Username:</h1>
      <h5 class="card-title">{{ user.username }}</h5>
      <h1>E-mail:</h1>
      <p class="card-text mb-2">{{ user.email }}</p>
      <h1>Bio:</h1>
      <p class="card-text">{{ user.profile.bio }}</p>
    </div>

    {% if user not in current_user.friends.all and user != current_user %}
    <div>
      <a href="{% url 'friend:send-friend-request' user.pk %}">
        <button type="button" class="btn btn-success btn-lg btn-block mb-2">
        Send Friend Request
        </button>
      </a>
    </div>
    {% endif %}

    {% if sent_friend_request %}
    <div>
      <a href="{% url 'friend:cancel-friend-request' user.pk %}">
        <button type="button" class="btn btn-danger btn-lg btn-block mb-2">
        Cancel Friend Request
        </button>
      </a>
    </div>
    {% endif %}

    {% if user in current_user.friends.all and user != current_user %}
    <div>
      <a href="{% url 'messaging:direct-chat' user.pk %}">
        <button type="button" class="btn btn-info btn-lg btn-block mb-2">
        Message other user!
        </button>
      </a>
    </div>

    <div>
    <a id="videochat" href="{% url 'videochat:private-video-chat' user.pk %}">
      <button type="button" class="btn btn-success btn-lg btn-block mb-2">
      VideoChat other user!
      </button>
    </a>
    </div>
    {% endif %}


  </div>
  </div>

{{ user.pk|json_script:"videochat.pk" }}

<script type="text/javascript">

  let videochat_pk = JSON.parse(document.getElementById('videochat.pk').textContent);

  let handleSubmit = async (e) => {
      e.preventDefault()
      let room = videochat_pk

      let response = await fetch(`/get_token/?channel=${room}`)
      let data = await response.json()
      
      let UID = data.uid
      let token = data.token

      sessionStorage.setItem('UID', UID)
      sessionStorage.setItem('token', token)
      sessionStorage.setItem('room', room)

      window.open('/privatevideochat/'+videochat_pk+'/', '_self')
  }

  document.getElementById("videochat").addEventListener('click', handleSubmit)
</script>


{% endblock content %}